---
dir_map:
  ulib: /usr/lib
  bin: /usr/sbin
description: Command-line tool for interfering with a Wordpress installation
maintainer: "Avi Greenbury <ialoneambest@gmail.com>"
package: wptool
requires:
  perl: 0
  mysql-client: 0
  # For md5sum:
  coreutils: 0

